name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=5.0.1
  - python=3.8.8
  - r-dplyr
  - r-gglot2
  - r-reshape2
  - r-tidyverse
  - r-shiny
  - pip
  - pip:
    - pandas
    - matplotlib
    - numby
    - scipy
